#!/usr/bin/env zsh

dependencies=(
    "brew"
    "just"
    "cargo"
    "checkexec"
    "pipx"
    "pnpm"
    "speedscope"
)

install_dependency() {
    case ${1} in
        "brew")
            curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
            ;;
        "just")
            brew install just
            ;;
        "cargo")
            curl https://sh.rustup.rs -sSf | sh
            ;;
        "checkexec")
            cargo install checkexec
            ;;
        "pipx")
            brew install pipx; pipx ensurepath
            ;;
        "pnpm")
            curl -fsSL https://get.pnpm.io/install.sh | sh -
            ;;
        "speedscope")
            pnpm add -g speedscope
            ;;
    esac
}

check_dependency() {
    if command -v "${1}" &>/dev/null; then
        echo "\"${1}\" installed."
    else
        echo "Installing ${1}..."
        install_dependency "${1}"
    fi
}

for dependency in "${dependencies[@]}"; do
    check_dependency "${dependency}"
done
