[tool.poetry]
name = "agni"
version = "0.1.0"
description = "Create combination-tone matrices."
authors = ["Ben Rosen <benjamin.j.rosen@gmail.com>"]
readme = "README.md"

[tool.black]
preview = true
line-length = 79

[tool.flake8]
extend-ignore = "E203"

[tool.isort]
profile = "black"

[tool.poetry.scripts]
agni = "agni.main:agni"

[tool.poetry.dependencies]
python = "^3.10"
typer = {extras = ["all"], version = "^0.6.1"}
abjad = { version = "^3.13", python = ">=3.10,<3.12" }
supriya = "^22.9b1"
abjad-ext-rmakers = "^3.14"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
bpython = "^0.23"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
