[project]
name = "agni"
version = "0.1.0"
description = """\
Music compositional tools inspired by the techniques of Claude Vivier
"""
authors = [{ name = "Ben Rosen", email = "benjamin.j.rosen@gmail.com" }]
readme = "README.md"
keywords = ["claude vivier", "lilypond", "music notation", "music", "spectral"]
requires-python = ">=3.13"
dependencies = [
  "abjad-ext-rmakers>=3.21",
  "abjad>=3.21",
  "cyclopts>=3.9.0",
  "more-itertools>=10.6.0",
  "supriya>=24.3b2",
]

[project.urls]
repository = "https://github.com/tymbalodeon/agni"

[project.scripts]
agni = "agni.main:agni"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
exclude = [".git", ".ruff_cache", ".venv", "build", "dist"]
line-length = 79
indent-width = 4

[dependency-groups]
dev = ["bpython>=0.25", "pytest>=8.3.4"]
