[project]
name = "agni"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "abjad==3.23",
  "abjad-ext-rmakers>=3.21",
  "cyclopts>=3.9.0",
  "more-itertools>=10.6.0",
  "supriya>=24.3b2",
]
description = "Music compositional tools inspired by the techniques of Claude Vivier"
keywords = ["claude vivier", "lilypond", "music notation", "music", "spectral"]

[[project.authors]]
name = "Ben Rosen"
email = "benjamin.j.rosen@gmail.com"

[project.urls]
repository = "https://github.com/tymbalodeon/agni"

[project.scripts]
agni = "agni.main:agni"

[dependency-groups]
dev = ["bpython>=0.25", "fawltydeps>=0.19.0", "pytest>=8.3.4"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
venvPath = "."
venv = ".venv"
