[project]
name = "agni"
version = "0.2.0"
description = """\
Music compositional tools \
inspired by the techniques of Claude Vivier
"""
authors = [
    {name = "Ben Rosen", email = "benjamin.j.rosen@gmail.com"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"
keywords = [
    "claude vivier",
    "lilypond",
    "music notation",
    "music",
    "spectral",
]
dependencies = [
    "typer[all]>=0.9.0",
    "abjad>=3.19",
    "supriya>=23.10b0",
    "abjad-ext-rmakers>=3.19",
    "more-itertools>=10.1.0",
]

[project.urls]
repository = "https://github.com/tymbalodeon/agni"

[project.scripts]
agni = "agni.main:agni"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "build",
    "dist",
]
line-length = 79
indent-width = 4

[tool.pdm.dev-dependencies]
dev = [
    "pre-commit>=3.5.0",
    "bpython>=0.24",
    "py-spy>=0.3.14",
    "pytest>=7.4.3",
    "coverage>=7.3.2",
    "ruff>=0.1.7",
    "pyright>=1.1.338",
]
