[tool.poetry]
name = "agni"
version = "0.1.0"
description = "Create combination-tone matrices."
authors = ["Ben Rosen <benjamin.j.rosen@gmail.com>"]
readme = "README.md"

[tool.black]
preview = true
line-length = 79

[tool.flake8]
extend-ignore = "E203"

[tool.isort]
profile = "black"

[tool.poetry.scripts]
agni = "agni.main:agni"

[tool.poetry.dependencies]
python = "^3.11"
typer = {extras = ["all"], version = "^0.7.0"}
abjad = "^3.15"
supriya = "^22.12b1"
abjad-ext-rmakers = "^3.15"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.21.0"
bpython = "^0.23"
py-spy = "^0.3.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
