[project]
name = "agni"
version = "0.2.0"
description = """\
    Music compositional tools inspired by the techniques of Claude Vivier \
"""
authors = [
    {name = "Ben Rosen", email = "benjamin.j.rosen@gmail.com"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    "typer[all]>=0.9.0",
    "abjad>=3.18",
    "supriya>=23.6b0",
    "abjad-ext-rmakers>=3.18",
    "more-itertools>=9.1.0",
]

[project.urls]
repository = "https://github.com/tymbalodeon/agni"

[project.scripts]
agni = "agni.main:agni"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
preview = true
line-length = 79

[tool.flake8]
extend-ignore = "E203"

[tool.isort]
profile = "black"

[tool.pdm.dev-dependencies]
dev = [
    "pre-commit>=3.3.3",
    "bpython>=0.24",
    "py-spy>=0.3.14",
    "pytest>=7.4.0",
    "coverage>=7.2.7",
    "pyre-check>=0.9.19",
    "mypy>=1.7.1",
    "fb-sapp>=0.5.1",
    "ruff>=0.1.6",
]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
line-length = 79
indent-width = 4
