set working-directory := "../.."

# View help text
@help *args:
    .environments/python/scripts/help.nu {{ args }}

# Add dependencies
@add *args:
    .environments/python/scripts/add.nu {{ args }}

# Check python files
@check *args:
    .environments/python/scripts/check.nu {{ args }}

# Show application dependencies
@dependencies *args:
    .environments/python/scripts/dependencies.nu {{ args }}

alias deps := dependencies

# Format python files
@format *args:
    .environments/python/scripts/format.nu {{ args }}

alias fmt := format

# Lint python files
@lint *args:
    .environments/python/scripts/lint.nu {{ args }}

# Manage python version
@pin *args:
    .environments/python/scripts/pin.nu {{ args }}

# Profile a command and view results
@profile *args:
    .environments/python/scripts/profile.nu {{ args }}

# Remove dependencies
@remove *args:
    .environments/python/scripts/remove.nu {{ args }}

alias rm := remove

# Run the application
@run *args:
    .environments/python/scripts/run.nu {{ args }}

# Open an interactive python shell
@shell *args:
    .environments/python/scripts/shell.nu {{ args }}

alias sh := shell

# Run tests
@test *args:
    .environments/python/scripts/test.nu {{ args }}

# Update dependencies
@update *args:
    .environments/python/scripts/update.nu {{ args }}

alias up := update

# Build and install the application
@build *args:
    .environments/python/scripts/build.nu {{ args }}
